#############################################################################
# Makefile for building: Serial
# Generated by qmake (2.01a) (Qt 4.8.0) on: Thu Jan 8 10:42:27 2015
# Project:  Serial.pro
# Template: app
# Command: /usr/linux-qt4.8.0/bin/qmake -o Makefile Serial.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/linux-qt4.8.0/mkspecs/linux-g++ -I. -I/usr/linux-qt4.8.0/include/QtCore -I/usr/linux-qt4.8.0/include/QtGui -I/usr/linux-qt4.8.0/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/linux-qt4.8.0/lib
LIBS          = $(SUBLIBS)  -L/usr/linux-qt4.8.0/lib -lQtGui -L/usr/linux-qt4.8.0/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/linux-qt4.8.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		serial.cpp \
		serialtest.cpp 
OBJECTS       = main.o \
		serial.o \
		serialtest.o
DIST          = /usr/linux-qt4.8.0/mkspecs/common/unix.conf \
		/usr/linux-qt4.8.0/mkspecs/common/linux.conf \
		/usr/linux-qt4.8.0/mkspecs/common/gcc-base.conf \
		/usr/linux-qt4.8.0/mkspecs/common/gcc-base-unix.conf \
		/usr/linux-qt4.8.0/mkspecs/common/g++-base.conf \
		/usr/linux-qt4.8.0/mkspecs/common/g++-unix.conf \
		/usr/linux-qt4.8.0/mkspecs/qconfig.pri \
		/usr/linux-qt4.8.0/mkspecs/modules/qt_webkit_version.pri \
		/usr/linux-qt4.8.0/mkspecs/features/qt_functions.prf \
		/usr/linux-qt4.8.0/mkspecs/features/qt_config.prf \
		/usr/linux-qt4.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/linux-qt4.8.0/mkspecs/features/default_pre.prf \
		/usr/linux-qt4.8.0/mkspecs/features/release.prf \
		/usr/linux-qt4.8.0/mkspecs/features/default_post.prf \
		/usr/linux-qt4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/linux-qt4.8.0/mkspecs/features/warn_on.prf \
		/usr/linux-qt4.8.0/mkspecs/features/qt.prf \
		/usr/linux-qt4.8.0/mkspecs/features/unix/thread.prf \
		/usr/linux-qt4.8.0/mkspecs/features/moc.prf \
		/usr/linux-qt4.8.0/mkspecs/features/resources.prf \
		/usr/linux-qt4.8.0/mkspecs/features/uic.prf \
		/usr/linux-qt4.8.0/mkspecs/features/yacc.prf \
		/usr/linux-qt4.8.0/mkspecs/features/lex.prf \
		/usr/linux-qt4.8.0/mkspecs/features/include_source_dir.prf \
		Serial.pro
QMAKE_TARGET  = Serial
DESTDIR       = 
TARGET        = Serial

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Serial.pro  /usr/linux-qt4.8.0/mkspecs/linux-g++/qmake.conf /usr/linux-qt4.8.0/mkspecs/common/unix.conf \
		/usr/linux-qt4.8.0/mkspecs/common/linux.conf \
		/usr/linux-qt4.8.0/mkspecs/common/gcc-base.conf \
		/usr/linux-qt4.8.0/mkspecs/common/gcc-base-unix.conf \
		/usr/linux-qt4.8.0/mkspecs/common/g++-base.conf \
		/usr/linux-qt4.8.0/mkspecs/common/g++-unix.conf \
		/usr/linux-qt4.8.0/mkspecs/qconfig.pri \
		/usr/linux-qt4.8.0/mkspecs/modules/qt_webkit_version.pri \
		/usr/linux-qt4.8.0/mkspecs/features/qt_functions.prf \
		/usr/linux-qt4.8.0/mkspecs/features/qt_config.prf \
		/usr/linux-qt4.8.0/mkspecs/features/exclusive_builds.prf \
		/usr/linux-qt4.8.0/mkspecs/features/default_pre.prf \
		/usr/linux-qt4.8.0/mkspecs/features/release.prf \
		/usr/linux-qt4.8.0/mkspecs/features/default_post.prf \
		/usr/linux-qt4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/linux-qt4.8.0/mkspecs/features/warn_on.prf \
		/usr/linux-qt4.8.0/mkspecs/features/qt.prf \
		/usr/linux-qt4.8.0/mkspecs/features/unix/thread.prf \
		/usr/linux-qt4.8.0/mkspecs/features/moc.prf \
		/usr/linux-qt4.8.0/mkspecs/features/resources.prf \
		/usr/linux-qt4.8.0/mkspecs/features/uic.prf \
		/usr/linux-qt4.8.0/mkspecs/features/yacc.prf \
		/usr/linux-qt4.8.0/mkspecs/features/lex.prf \
		/usr/linux-qt4.8.0/mkspecs/features/include_source_dir.prf \
		/usr/linux-qt4.8.0/lib/libQtGui.prl \
		/usr/linux-qt4.8.0/lib/libQtCore.prl
	$(QMAKE) -o Makefile Serial.pro
/usr/linux-qt4.8.0/mkspecs/common/unix.conf:
/usr/linux-qt4.8.0/mkspecs/common/linux.conf:
/usr/linux-qt4.8.0/mkspecs/common/gcc-base.conf:
/usr/linux-qt4.8.0/mkspecs/common/gcc-base-unix.conf:
/usr/linux-qt4.8.0/mkspecs/common/g++-base.conf:
/usr/linux-qt4.8.0/mkspecs/common/g++-unix.conf:
/usr/linux-qt4.8.0/mkspecs/qconfig.pri:
/usr/linux-qt4.8.0/mkspecs/modules/qt_webkit_version.pri:
/usr/linux-qt4.8.0/mkspecs/features/qt_functions.prf:
/usr/linux-qt4.8.0/mkspecs/features/qt_config.prf:
/usr/linux-qt4.8.0/mkspecs/features/exclusive_builds.prf:
/usr/linux-qt4.8.0/mkspecs/features/default_pre.prf:
/usr/linux-qt4.8.0/mkspecs/features/release.prf:
/usr/linux-qt4.8.0/mkspecs/features/default_post.prf:
/usr/linux-qt4.8.0/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/linux-qt4.8.0/mkspecs/features/warn_on.prf:
/usr/linux-qt4.8.0/mkspecs/features/qt.prf:
/usr/linux-qt4.8.0/mkspecs/features/unix/thread.prf:
/usr/linux-qt4.8.0/mkspecs/features/moc.prf:
/usr/linux-qt4.8.0/mkspecs/features/resources.prf:
/usr/linux-qt4.8.0/mkspecs/features/uic.prf:
/usr/linux-qt4.8.0/mkspecs/features/yacc.prf:
/usr/linux-qt4.8.0/mkspecs/features/lex.prf:
/usr/linux-qt4.8.0/mkspecs/features/include_source_dir.prf:
/usr/linux-qt4.8.0/lib/libQtGui.prl:
/usr/linux-qt4.8.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Serial.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Serial1.0.0 || $(MKDIR) .tmp/Serial1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Serial1.0.0/ && $(COPY_FILE) --parents serial.h serialtest.h .tmp/Serial1.0.0/ && $(COPY_FILE) --parents main.cpp serial.cpp serialtest.cpp .tmp/Serial1.0.0/ && (cd `dirname .tmp/Serial1.0.0` && $(TAR) Serial1.0.0.tar Serial1.0.0 && $(COMPRESS) Serial1.0.0.tar) && $(MOVE) `dirname .tmp/Serial1.0.0`/Serial1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Serial1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp serialtest.h \
		serial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

serial.o: serial.cpp serial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serial.o serial.cpp

serialtest.o: serialtest.cpp serialtest.h \
		serial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialtest.o serialtest.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

